// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.Infrastructure.Persistence;

#nullable disable

namespace Quiz.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725165348_SeedMvpQuestions")]
    partial class SeedMvpQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Quiz.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("IdealAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ideal_answer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.HasIndex("Topic")
                        .HasDatabaseName("ix_questions_topic");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdealAnswer = "IEnumerable<T> выполняет дальнейшие операции в памяти через LINQ to Objects. IQueryable<T> хранит expression tree, который провайдер переводит во внешний запрос, например SQL. IQueryable не стоит выпускать за границы слоя данных: это размывает ответственность, усложняет тестирование и позволяет вызывающему сформировать неэффективный запрос.",
                            Text = "В чём разница между IEnumerable<T> и IQueryable<T> и где проходит граница их безопасного использования?",
                            Topic = "CSharp"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IdealAnswer = "Компилятор преобразует async-метод в конечный автомат. При незавершённой await-операции управление возвращается вызывающему коду, а продолжение планируется после завершения Task. Для I/O поток обычно не блокируется и новый поток не требуется; пул потоков нужен преимущественно для CPU-bound работы.",
                            Text = "Как работает async/await в C# и почему async-метод не обязательно создаёт новый поток?",
                            Topic = "CSharp"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IdealAnswer = "Class подходит для объектов с идентичностью и изменяемым жизненным циклом. Record удобен для value-like моделей и DTO благодаря value equality и with-выражениям. Struct стоит применять для небольших неизменяемых значений, которые часто создаются и не требуют наследования; крупные структуры увеличивают стоимость копирования.",
                            Text = "Когда следует использовать record, class и struct?",
                            Topic = "CSharp"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            IdealAnswer = "Span<T> представляет непрерывный участок памяти без дополнительных аллокаций и может ссылаться на массив, stackalloc или unmanaged memory. Это ref struct, поэтому он не может храниться в heap-объекте, использоваться через await или yield. Memory<T> можно хранить в объектах и передавать через async-границы, получая Span при синхронной обработке.",
                            Text = "Объясните назначение Span<T> и Memory<T>. Какие ограничения есть у Span<T>?",
                            Topic = "CSharp"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            IdealAnswer = "Токен передают по всей цепочке вызовов и регулярно проверяют через ThrowIfCancellationRequested либо прокидывают в поддерживающие его API. Владелец CancellationTokenSource отвечает за отмену и освобождение ресурса. OperationCanceledException не следует превращать в обычную ошибку: она отражает ожидаемое завершение по запросу.",
                            Text = "Как правильно реализовать отмену длительной операции с помощью CancellationToken?",
                            Topic = "CSharp"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            IdealAnswer = "Tracking-запросы помещают сущности в ChangeTracker, поддерживают identity resolution и позволяют сохранить изменения через SaveChanges. AsNoTracking уменьшает расход памяти и CPU для read-only сценариев. Для сложных read-only графов возможен AsNoTrackingWithIdentityResolution, который устраняет дубликаты объектов без постоянного tracking.",
                            Text = "Чем отличаются tracking и no-tracking запросы в Entity Framework Core?",
                            Topic = "EntityFramework"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            IdealAnswer = "N+1 возникает, когда после одного запроса списка выполняется отдельный запрос для каждой записи. Её видно по логам SQL, профилировщику и метрикам количества запросов. Обычно помогают проекция Select, осознанный Include, пакетная загрузка и отключение неуместной lazy loading.",
                            Text = "Что такое проблема N+1 и как её обнаружить и устранить в EF Core?",
                            Topic = "EntityFramework"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            IdealAnswer = "Include нужен, когда требуется материализовать и изменять граф доменных сущностей. Для чтения и API-ответов предпочтительнее Select в DTO: он выбирает только необходимые столбцы, уменьшает объём данных и часто формирует более простой SQL. Include не влияет на проекцию, если итоговый результат уже не является сущностью.",
                            Text = "Когда использовать Include, а когда проекцию Select?",
                            Topic = "EntityFramework"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            IdealAnswer = "В модель добавляют concurrency token, часто rowversion или явно управляемую версию. EF включает исходное значение токена в условие UPDATE/DELETE и при конфликте выбрасывает DbUpdateConcurrencyException. Приложение должно выбрать стратегию: повтор, слияние изменений или сообщение пользователю.",
                            Text = "Как организовать optimistic concurrency в EF Core?",
                            Topic = "EntityFramework"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            IdealAnswer = "DbContext представляет unit of work и обычно живёт в рамках одной операции. Он не является thread-safe: параллельные запросы и изменения одного экземпляра приводят к исключениям и повреждению состояния tracking. В долгоживущих процессах и Blazor Server применяют короткие scope, transient context или IDbContextFactory.",
                            Text = "Почему DbContext имеет scoped lifetime и какие риски возникают при его совместном использовании между потоками?",
                            Topic = "EntityFramework"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            IdealAnswer = "Direct маршрутизирует по точному routing key. Topic поддерживает шаблоны с * и #. Fanout отправляет сообщение во все связанные очереди, игнорируя ключ. Headers использует набор заголовков и применяется реже из-за большей сложности и стоимости сопоставления.",
                            Text = "Чем отличаются direct, topic, fanout и headers exchanges в RabbitMQ?",
                            Topic = "RabbitMQ"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            IdealAnswer = "Сообщения публикуют как persistent в durable exchange/queue, используют publisher confirms, а consumer отправляет ack только после успешной обработки. При сбое сообщение доставляется повторно, поэтому consumer обязан быть идемпотентным, например хранить идентификаторы обработанных сообщений или использовать естественный уникальный ключ.",
                            Text = "Как обеспечить at-least-once delivery и что должен делать consumer?",
                            Topic = "RabbitMQ"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            IdealAnswer = "Dead-letter exchange получает сообщения, которые были rejected/nacked без requeue, истекли по TTL или вытеснены ограничением длины очереди. Он позволяет отделить проблемные сообщения, организовать retry с задержкой и сохранить данные для анализа вместо бесконечного цикла повторной доставки.",
                            Text = "Что такое dead-letter exchange и для чего он нужен?",
                            Topic = "RabbitMQ"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            IdealAnswer = "Prefetch ограничивает число неподтверждённых сообщений у consumer. Большое значение повышает throughput, но увеличивает память и может привести к неравномерному распределению. Малое улучшает fairness и время восстановления, но увеличивает влияние сетевых задержек. Значение подбирают по времени обработки и допустимому параллелизму.",
                            Text = "Как prefetch влияет на производительность и справедливость распределения сообщений?",
                            Topic = "RabbitMQ"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            IdealAnswer = "Очередь сохраняет порядок публикации, но несколько consumers, повторная доставка, nack/requeue и разное время обработки меняют наблюдаемый порядок завершения. Если порядок критичен, используют один consumer или партиционирование по ключу и контролируют повторную обработку.",
                            Text = "Почему порядок сообщений в RabbitMQ нельзя считать абсолютной гарантией?",
                            Topic = "RabbitMQ"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            IdealAnswer = "MVCC хранит несколько версий строк, позволяя читателям и писателям меньше блокировать друг друга. UPDATE создаёт новую версию, а старая становится dead tuple после завершения видимых транзакций. VACUUM освобождает место для повторного использования и предотвращает переполнение transaction ID; autovacuum автоматизирует процесс.",
                            Text = "Как MVCC работает в PostgreSQL и зачем нужен VACUUM?",
                            Topic = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            IdealAnswer = "B-tree — универсальный выбор для равенства, диапазонов и сортировки. Hash оптимизирован для равенства, но обычно не даёт преимуществ над B-tree. GIN эффективен для составных значений, массивов, JSONB и полнотекстового поиска. GiST поддерживает расширяемые стратегии, геометрию, диапазоны и nearest-neighbor поиск.",
                            Text = "В чём разница между B-tree, Hash, GIN и GiST индексами?",
                            Topic = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            IdealAnswer = "Сравнивают estimated и actual rows, время узлов, число loops, способ доступа и операции сортировки/хеширования. Большие расхождения строк указывают на устаревшую статистику или коррелированные данные. Seq Scan не всегда плох: он разумен для маленькой таблицы или выборки большой доли строк.",
                            Text = "Как читать EXPLAIN ANALYZE и какие признаки указывают на проблему?",
                            Topic = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            IdealAnswer = "PostgreSQL предоставляет Read Committed, Repeatable Read и Serializable; Read Uncommitted ведёт себя как Read Committed. Serializable нужен, когда результат параллельных транзакций должен быть эквивалентен последовательному выполнению. Он может завершить транзакцию serialization failure, поэтому приложение обязано поддерживать retry.",
                            Text = "Какие уровни изоляции транзакций поддерживает PostgreSQL и когда нужен Serializable?",
                            Topic = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            IdealAnswer = "Последовательное чтение может быть дешевле для маленькой таблицы или низкой селективности. Причинами также бывают несовместимое выражение или преобразование типа, устаревшая статистика, ведущий wildcard, неподходящий порядок составного индекса и функции без соответствующего expression index.",
                            Text = "Почему индекс может не использоваться планировщиком PostgreSQL?",
                            Topic = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            IdealAnswer = "Агрегат — граница строгой согласованности и транзакции. Внешний код обращается только к Aggregate Root, который защищает инварианты. Другие агрегаты связываются по идентификатору, а не через большой объектный граф; eventual consistency между агрегатами реализуют доменными событиями.",
                            Text = "Какие границы определяют агрегат в DDD?",
                            Topic = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            IdealAnswer = "CQRS полезен, когда модели чтения и изменения заметно различаются, нужны независимое масштабирование, сложные бизнес-команды или разные требования к консистентности. Для простого CRUD разделение добавляет типы, обработчики и инфраструктуру без достаточной выгоды. CQRS не требует автоматически отдельных баз или event sourcing.",
                            Text = "Когда CQRS полезен, а когда становится лишней сложностью?",
                            Topic = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            IdealAnswer = "Выбор зависит от организационных границ, независимого масштабирования, скорости изменений и операционной зрелости. Модульный монолит часто является лучшей стартовой точкой: сохраняет простые транзакции и деплой, но дисциплинирует границы. Микросервисы оправданы, когда независимость команд и частей системы окупает распределённую сложность.",
                            Text = "Как выбрать между монолитом, модульным монолитом и микросервисами?",
                            Topic = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            IdealAnswer = "Изменение бизнес-данных и запись сообщения outbox выполняются в одной локальной транзакции. Отдельный publisher читает outbox и доставляет сообщения брокеру с повторами. Это устраняет dual-write между БД и брокером, но потребители всё равно должны быть идемпотентными из-за возможных дубликатов.",
                            Text = "Что такое transactional outbox и какую проблему он решает?",
                            Topic = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            IdealAnswer = "Операция должна давать один бизнес-результат при повторном запросе. Используют idempotency key, уникальное ограничение и атомарную запись результата, сохраняя ответ для повторного возврата. Важно определить срок хранения ключей и отличать повтор того же запроса от конфликта с другим содержимым.",
                            Text = "Как проектировать идемпотентный API или обработчик команды?",
                            Topic = "Architecture"
                        });
                });

            modelBuilder.Entity("Quiz.Domain.Questions.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("question_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_answers_user_id_question_id");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("Quiz.Domain.Questions.UserAnswer", b =>
                {
                    b.HasOne("Quiz.Domain.Questions.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quiz.Domain.Questions.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
